import styles from "./layout.module.css";
import localFont from "next/font/local";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={styles.body}>{children}</body>
    </html>
  );
}
